/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package edu.nps.portlet.linkscanner.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.InfrastructureUtil;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import edu.nps.portlet.linkscanner.service.LinkScannerURLStatusService;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the link scanner u r l status remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link edu.nps.portlet.linkscanner.service.impl.LinkScannerURLStatusServiceImpl}.
 * </p>
 *
 * @author Craig Vershaw
 * @see edu.nps.portlet.linkscanner.service.impl.LinkScannerURLStatusServiceImpl
 * @see edu.nps.portlet.linkscanner.service.LinkScannerURLStatusServiceUtil
 * @generated
 */
public abstract class LinkScannerURLStatusServiceBaseImpl
	extends BaseServiceImpl implements LinkScannerURLStatusService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link edu.nps.portlet.linkscanner.service.LinkScannerURLStatusServiceUtil} to access the link scanner u r l status remote service.
	 */

	/**
	 * Returns the link scanner u r l status local service.
	 *
	 * @return the link scanner u r l status local service
	 */
	public edu.nps.portlet.linkscanner.service.LinkScannerURLStatusLocalService getLinkScannerURLStatusLocalService() {
		return linkScannerURLStatusLocalService;
	}

	/**
	 * Sets the link scanner u r l status local service.
	 *
	 * @param linkScannerURLStatusLocalService the link scanner u r l status local service
	 */
	public void setLinkScannerURLStatusLocalService(
		edu.nps.portlet.linkscanner.service.LinkScannerURLStatusLocalService linkScannerURLStatusLocalService) {
		this.linkScannerURLStatusLocalService = linkScannerURLStatusLocalService;
	}

	/**
	 * Returns the link scanner u r l status remote service.
	 *
	 * @return the link scanner u r l status remote service
	 */
	public edu.nps.portlet.linkscanner.service.LinkScannerURLStatusService getLinkScannerURLStatusService() {
		return linkScannerURLStatusService;
	}

	/**
	 * Sets the link scanner u r l status remote service.
	 *
	 * @param linkScannerURLStatusService the link scanner u r l status remote service
	 */
	public void setLinkScannerURLStatusService(
		edu.nps.portlet.linkscanner.service.LinkScannerURLStatusService linkScannerURLStatusService) {
		this.linkScannerURLStatusService = linkScannerURLStatusService;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = InfrastructureUtil.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = edu.nps.portlet.linkscanner.service.LinkScannerURLStatusLocalService.class)
	protected edu.nps.portlet.linkscanner.service.LinkScannerURLStatusLocalService linkScannerURLStatusLocalService;
	@BeanReference(type = edu.nps.portlet.linkscanner.service.LinkScannerURLStatusService.class)
	protected edu.nps.portlet.linkscanner.service.LinkScannerURLStatusService linkScannerURLStatusService;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LinkScannerURLStatusServiceClpInvoker _clpInvoker = new LinkScannerURLStatusServiceClpInvoker();
}